# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fibonacciSquence = [1, 2]
evenFibonacci = []
i = 1

while True:
    fibonacciSquence.append(fibonacciSquence[i - 1] + fibonacciSquence[i])
    i += 1
    if fibonacciSquence[i] > 4000000:
        break
for i in fibonacciSquence:
    if i % 2 == 0:
        evenFibonacci.append(i)

print('The sum of your series is: %i' % sum(evenFibonacci))
